version: '3.8'

services:
  app:
    image: floorplangen-app:latest
    build: .
    volumes:
      - .:/work
    ports:
      - "8888:8888"
      - "5678:5678" # デバッグ用
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    working_dir: /work